"""empty message

Revision ID: d6c982e87de2
Revises: 
Create Date: 2020-02-14 14:12:53.187613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c982e87de2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plazas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_plaza', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('isAdmin', sa.Boolean(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mesas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_mesa', sa.String(length=50), nullable=False),
    sa.Column('plaza_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plaza_id'], ['plazas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('info_pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_mesa', sa.Integer(), nullable=False),
    sa.Column('abierto', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_mesa'], ['mesas.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_item', sa.Integer(), nullable=False),
    sa.Column('id_info_pedidos', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_info_pedidos'], ['info_pedidos.id'], ),
    sa.ForeignKeyConstraint(['id_item'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedidos')
    op.drop_table('info_pedidos')
    op.drop_table('mesas')
    op.drop_table('items')
    op.drop_table('users')
    op.drop_table('plazas')
    op.drop_table('categories')
    # ### end Alembic commands ###
